/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auftraggeber": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Auftraggeber */
        get: operations["list_auftraggeber_api_auftraggeber_get"];
        put?: never;
        /** Create Auftraggeber */
        post: operations["create_auftraggeber_api_auftraggeber_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auftraggeber/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auftraggeber */
        get: operations["get_auftraggeber_api_auftraggeber__id__get"];
        /** Update Auftraggeber */
        put: operations["update_auftraggeber_api_auftraggeber__id__put"];
        post?: never;
        /** Delete Auftraggeber */
        delete: operations["delete_auftraggeber_api_auftraggeber__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kontakt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Kontakt */
        get: operations["list_kontakt_api_kontakt_get"];
        put?: never;
        /** Create Kontakt */
        post: operations["create_kontakt_api_kontakt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kontakt/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kontakt */
        get: operations["get_kontakt_api_kontakt__id__get"];
        /** Update Kontakt */
        put: operations["update_kontakt_api_kontakt__id__put"];
        post?: never;
        /** Delete Kontakt */
        delete: operations["delete_kontakt_api_kontakt__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projekt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projekt */
        get: operations["list_projekt_api_projekt_get"];
        put?: never;
        /** Create Projekt */
        post: operations["create_projekt_api_projekt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projekt/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Projekt */
        get: operations["get_projekt_api_projekt__id__get"];
        /** Update Projekt */
        put: operations["update_projekt_api_projekt__id__put"];
        post?: never;
        /** Delete Projekt */
        delete: operations["delete_projekt_api_projekt__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projekt/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Projekt Status */
        patch: operations["patch_projekt_status_api_projekt__id__status_patch"];
        trace?: never;
    };
    "/api/arbeitszeit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Arbeitszeit */
        get: operations["list_arbeitszeit_api_arbeitszeit_get"];
        put?: never;
        /** Create Arbeitszeit */
        post: operations["create_arbeitszeit_api_arbeitszeit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arbeitszeit/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Arbeitszeit */
        get: operations["get_arbeitszeit_api_arbeitszeit__id__get"];
        /** Update Arbeitszeit */
        put: operations["update_arbeitszeit_api_arbeitszeit__id__put"];
        post?: never;
        /** Delete Arbeitszeit */
        delete: operations["delete_arbeitszeit_api_arbeitszeit__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arbeitszeit/{id}/freigabe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve Arbeitszeit */
        patch: operations["approve_arbeitszeit_api_arbeitszeit__id__freigabe_patch"];
        trace?: never;
    };
    "/api/arbeitszeit/{id}/korrektur": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Korrektur Arbeitszeit */
        post: operations["korrektur_arbeitszeit_api_arbeitszeit__id__korrektur_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + DB reachability. No tenant context required.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArbeitszeitCreate */
        ArbeitszeitCreate: {
            /**
             * App User Id
             * Format: uuid
             */
            app_user_id: string;
            /** Projekt Id */
            projekt_id?: string | null;
            /**
             * Start Zeit
             * Format: date-time
             */
            start_zeit: string;
            /** End Zeit */
            end_zeit?: string | null;
            /**
             * Pause Minuten
             * @default 0
             */
            pause_minuten: number;
            /** Art */
            art?: string | null;
        };
        /** ArbeitszeitFreigabe */
        ArbeitszeitFreigabe: {
            /** Row Version */
            row_version: number;
        };
        /**
         * ArbeitszeitKorrektur
         * @description Fields for the new correcting row. app_user_id is inherited from the
         *     original frozen entry so the corrected hours stay attributed to the same
         *     employee.
         */
        ArbeitszeitKorrektur: {
            /**
             * Start Zeit
             * Format: date-time
             */
            start_zeit: string;
            /** End Zeit */
            end_zeit?: string | null;
            /**
             * Pause Minuten
             * @default 0
             */
            pause_minuten: number;
            /** Art */
            art?: string | null;
            /** Projekt Id */
            projekt_id?: string | null;
        };
        /** ArbeitszeitRead */
        ArbeitszeitRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by: string;
            /** Row Version */
            row_version: number;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * App User Id
             * Format: uuid
             */
            app_user_id: string;
            /** Projekt Id */
            projekt_id?: string | null;
            /**
             * Start Zeit
             * Format: date-time
             */
            start_zeit: string;
            /** End Zeit */
            end_zeit?: string | null;
            /** Pause Minuten */
            pause_minuten: number;
            /** Dauer */
            dauer?: string | null;
            /** Art */
            art?: string | null;
            /**
             * Freigabe Status
             * @enum {string}
             */
            freigabe_status: "offen" | "freigegeben";
            /** Freigegeben Am */
            freigegeben_am?: string | null;
            /** Freigegeben Von */
            freigegeben_von?: string | null;
            /** Korrektur Von Id */
            korrektur_von_id?: string | null;
        };
        /** ArbeitszeitUpdate */
        ArbeitszeitUpdate: {
            /** Row Version */
            row_version: number;
            /**
             * Start Zeit
             * Format: date-time
             */
            start_zeit: string;
            /** End Zeit */
            end_zeit?: string | null;
            /**
             * Pause Minuten
             * @default 0
             */
            pause_minuten: number;
            /** Art */
            art?: string | null;
            /** Projekt Id */
            projekt_id?: string | null;
        };
        /** AuftraggeberCreate */
        AuftraggeberCreate: {
            /** Name */
            name: string;
            /** Kundennummer */
            kundennummer?: string | null;
            /** Typ */
            typ?: ("privat" | "gewerblich" | "oeffentlich") | null;
            /** Ust Idnr */
            ust_idnr?: string | null;
        };
        /** AuftraggeberRead */
        AuftraggeberRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by: string;
            /** Row Version */
            row_version: number;
            /** Deleted At */
            deleted_at?: string | null;
            /** Name */
            name: string;
            /** Kundennummer */
            kundennummer?: string | null;
            /** Typ */
            typ?: ("privat" | "gewerblich" | "oeffentlich") | null;
            /** Ust Idnr */
            ust_idnr?: string | null;
        };
        /** AuftraggeberUpdate */
        AuftraggeberUpdate: {
            /** Row Version */
            row_version: number;
            /** Name */
            name: string;
            /** Kundennummer */
            kundennummer?: string | null;
            /** Typ */
            typ?: ("privat" | "gewerblich" | "oeffentlich") | null;
            /** Ust Idnr */
            ust_idnr?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KontaktCreate */
        KontaktCreate: {
            /**
             * Auftraggeber Id
             * Format: uuid
             */
            auftraggeber_id: string;
            /** Name */
            name: string;
            /** Rolle */
            rolle?: string | null;
            /** Email */
            email?: string | null;
            /** Telefon */
            telefon?: string | null;
        };
        /** KontaktRead */
        KontaktRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by: string;
            /** Row Version */
            row_version: number;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Auftraggeber Id
             * Format: uuid
             */
            auftraggeber_id: string;
            /** Name */
            name: string;
            /** Rolle */
            rolle?: string | null;
            /** Email */
            email?: string | null;
            /** Telefon */
            telefon?: string | null;
        };
        /** KontaktUpdate */
        KontaktUpdate: {
            /** Row Version */
            row_version: number;
            /** Name */
            name: string;
            /** Rolle */
            rolle?: string | null;
            /** Email */
            email?: string | null;
            /** Telefon */
            telefon?: string | null;
        };
        /** ProjektCreate */
        ProjektCreate: {
            /**
             * Auftraggeber Id
             * Format: uuid
             */
            auftraggeber_id: string;
            /** Name */
            name: string;
            /** Nummer */
            nummer?: string | null;
            /** Site Adresse */
            site_adresse?: string | null;
            /** Regime */
            regime?: ("bgb" | "vob") | null;
            /** Abrechnungsart */
            abrechnungsart?: ("einheitspreis" | "pauschal") | null;
            /** Start Datum */
            start_datum?: string | null;
            /** End Datum */
            end_datum?: string | null;
            /** Abnahme Datum */
            abnahme_datum?: string | null;
            /** Abnahme Document Id */
            abnahme_document_id?: string | null;
        };
        /** ProjektRead */
        ProjektRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by: string;
            /** Row Version */
            row_version: number;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Auftraggeber Id
             * Format: uuid
             */
            auftraggeber_id: string;
            /** Nummer */
            nummer?: string | null;
            /** Name */
            name: string;
            /** Site Adresse */
            site_adresse?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "angelegt" | "kalkulation" | "beauftragt" | "in_ausfuehrung" | "abgenommen" | "abgerechnet" | "gewaehrleistung" | "abgeschlossen" | "pausiert" | "storniert";
            /** Status Vor Pause */
            status_vor_pause?: string | null;
            /** Regime */
            regime?: ("bgb" | "vob") | null;
            /** Abrechnungsart */
            abrechnungsart?: ("einheitspreis" | "pauschal") | null;
            /** Abnahme Datum */
            abnahme_datum?: string | null;
            /** Abnahme Document Id */
            abnahme_document_id?: string | null;
            /** Start Datum */
            start_datum?: string | null;
            /** End Datum */
            end_datum?: string | null;
        };
        /** ProjektStatusPatch */
        ProjektStatusPatch: {
            /**
             * Status
             * @enum {string}
             */
            status: "angelegt" | "kalkulation" | "beauftragt" | "in_ausfuehrung" | "abgenommen" | "abgerechnet" | "gewaehrleistung" | "abgeschlossen" | "pausiert" | "storniert";
            /** Row Version */
            row_version: number;
            /** Reason */
            reason?: string | null;
        };
        /** ProjektUpdate */
        ProjektUpdate: {
            /** Row Version */
            row_version: number;
            /** Name */
            name: string;
            /**
             * Auftraggeber Id
             * Format: uuid
             */
            auftraggeber_id: string;
            /** Site Adresse */
            site_adresse?: string | null;
            /** Regime */
            regime?: ("bgb" | "vob") | null;
            /** Abrechnungsart */
            abrechnungsart?: ("einheitspreis" | "pauschal") | null;
            /** Start Datum */
            start_datum?: string | null;
            /** End Datum */
            end_datum?: string | null;
            /** Abnahme Datum */
            abnahme_datum?: string | null;
            /** Abnahme Document Id */
            abnahme_document_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_auftraggeber_api_auftraggeber_get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuftraggeberRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_auftraggeber_api_auftraggeber_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuftraggeberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuftraggeberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auftraggeber_api_auftraggeber__id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuftraggeberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_auftraggeber_api_auftraggeber__id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuftraggeberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuftraggeberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_auftraggeber_api_auftraggeber__id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_kontakt_api_kontakt_get: {
        parameters: {
            query?: {
                auftraggeber_id?: string | null;
            };
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KontaktRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_kontakt_api_kontakt_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KontaktCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KontaktRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kontakt_api_kontakt__id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KontaktRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_kontakt_api_kontakt__id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KontaktUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KontaktRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_kontakt_api_kontakt__id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projekt_api_projekt_get: {
        parameters: {
            query?: {
                status?: ("angelegt" | "kalkulation" | "beauftragt" | "in_ausfuehrung" | "abgenommen" | "abgerechnet" | "gewaehrleistung" | "abgeschlossen" | "pausiert" | "storniert") | null;
                auftraggeber_id?: string | null;
            };
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjektRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_projekt_api_projekt_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjektCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjektRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_projekt_api_projekt__id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjektRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_projekt_api_projekt__id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjektUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjektRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_projekt_api_projekt__id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_projekt_status_api_projekt__id__status_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjektStatusPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjektRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_arbeitszeit_api_arbeitszeit_get: {
        parameters: {
            query?: {
                projekt_id?: string | null;
                app_user_id?: string | null;
                freigabe_status?: ("offen" | "freigegeben") | null;
            };
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArbeitszeitRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_arbeitszeit_api_arbeitszeit_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArbeitszeitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArbeitszeitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_arbeitszeit_api_arbeitszeit__id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArbeitszeitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_arbeitszeit_api_arbeitszeit__id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArbeitszeitUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArbeitszeitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_arbeitszeit_api_arbeitszeit__id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_arbeitszeit_api_arbeitszeit__id__freigabe_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArbeitszeitFreigabe"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArbeitszeitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    korrektur_arbeitszeit_api_arbeitszeit__id__korrektur_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArbeitszeitKorrektur"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArbeitszeitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
